############################################################################
# board/k1/muse_pi_pro/src/Makefile
#
# SPDX-License-Identifier: Apache-2.0
############################################################################

include $(TOPDIR)/Make.defs

CSRCS = k1_boot.c

include $(TOPDIR)/boards/Board.mk
