#!/usr/bin/env bash
#
# SPDX-License-Identifier: Apache-2.0
#
# Build and package the RTL8852BS WPA2-PSK four-way handshake diagnostic image
# for the MUSE Pi Pro K1.
#
# The passphrase this step needs is a credential, so it never enters the source
# tree.  This script reads it from outside the repository, writes a generated
# defconfig outside the repository as well, and builds that instead of the
# committed profile.  The committed profile leaves the passphrase empty on
# purpose: built as it stands it reports ENOKEY and runs no handshake.
#
#   secret in:  K1_WIFI_PASSPHRASE and K1_WIFI_SSID from the environment, or
#               from ${K1_WIFI_PSK_ENV:-~/.config/k1-wifi-psk.env}
#   secret out: ${OPENVELA_ROOT}/cmake_out/k1-wpa-config/defconfig, mode 0600,
#               and from there the build's own .config and the image itself
#
# Everything that generated file reaches is outside this repository, but it is
# not nothing: the linked image carries the passphrase in its read-only data,
# because that is what a Kconfig string compiles to.  Do not publish the image
# in out/k1-wpa, and do not commit anything from cmake_out.  Nothing is printed
# by this script or by the firmware it builds that contains the value.
#
# Usage: build_k1_wpa.sh [--clean] [--jobs N] [--no-key]
#
#   --no-key  build the committed profile with no passphrase at all, which is
#             the honest way to check that the image still compiles without a
#             credential available

set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
CONTEST_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"
WORKSPACE_ROOT="${OPENVELA_ROOT:-$(cd -- "${CONTEST_ROOT}/.." && pwd)}"

PROFILE="${CONTEST_ROOT}/board/k1/muse_pi_pro/configs/wireless_wpa_diag"
GENERATED_DIR="${WORKSPACE_ROOT}/cmake_out/k1-wpa-config"
BUILD_DIR="${WORKSPACE_ROOT}/cmake_out/k1-wpa"
PACKAGE_DIR="${WORKSPACE_ROOT}/out/k1-wpa"
PSK_ENV="${K1_WIFI_PSK_ENV:-${HOME}/.config/k1-wifi-psk.env}"
JOBS="${K1_JOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || printf '8')}"
CLEAN=0
NO_KEY=0

fail() { printf 'build_k1_wpa: %s\n' "$1" >&2; exit 1; }

while [ $# -gt 0 ]; do
  case "$1" in
    --clean) CLEAN=1 ;;
    --jobs) shift; JOBS="$1" ;;
    --no-key) NO_KEY=1 ;;
    -h|--help) sed -n '1,30p' "$0"; exit 0 ;;
    *) fail "unknown option: $1" ;;
  esac
  shift
done

[ -f "${PROFILE}/defconfig" ] || fail "profile is missing: ${PROFILE}"

CONFIG_PATH="${PROFILE}"

if [ "${NO_KEY}" -eq 0 ]; then
  # The environment wins over the file, so a one-off build can pass the value
  # without it ever being stored.
  if [ -z "${K1_WIFI_PASSPHRASE:-}" ] && [ -r "${PSK_ENV}" ]; then
    set -a
    # shellcheck disable=SC1090
    . "${PSK_ENV}"
    set +a
  fi

  [ -n "${K1_WIFI_PASSPHRASE:-}" ] ||
    fail "no passphrase: set K1_WIFI_PASSPHRASE or write ${PSK_ENV}, or pass --no-key"

  length=${#K1_WIFI_PASSPHRASE}
  if [ "${length}" -lt 8 ] || [ "${length}" -gt 63 ]; then
    fail "the passphrase is not a length WPA2-PSK allows (8 to 63 characters)"
  fi

  # Kconfig string values are double quoted, so a backslash or a quote inside
  # the value has to be escaped rather than passed through.
  escape() {
    local value=$1
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    printf '%s' "${value}"
  }

  case "${GENERATED_DIR}" in
    "${CONTEST_ROOT}"/*|"${CONTEST_ROOT}")
      fail "refusing to write a credential inside the repository"
      ;;
  esac

  (
    umask 077
    mkdir -p "${GENERATED_DIR}"
    chmod 700 "${GENERATED_DIR}"
    {
      printf '# Generated by tools/build_k1_wpa.sh.  Contains a credential:\n'
      printf '# do not commit, do not publish, do not copy into the source tree.\n'
      printf '#include "%s/defconfig"\n' "${PROFILE}"
      printf 'CONFIG_K1_RTL8852BS2_RUNTIME_WPA_PASSPHRASE="%s"\n' \
        "$(escape "${K1_WIFI_PASSPHRASE}")"
      if [ -n "${K1_WIFI_SSID:-}" ]; then
        printf 'CONFIG_K1_RTL8852BS2_RUNTIME_WPA_SSID="%s"\n' \
          "$(escape "${K1_WIFI_SSID}")"
      fi
    } > "${GENERATED_DIR}/defconfig"
    chmod 600 "${GENERATED_DIR}/defconfig"
  )

  CONFIG_PATH="${GENERATED_DIR}"
  printf 'Passphrase:  configured, not printed\n'
  if [ -n "${K1_WIFI_SSID:-}" ]; then
    printf 'Network:     one named SSID from %s\n' "${PSK_ENV}"
  else
    printf 'Network:     any RSN access point in range that names itself\n'
  fi
  printf 'Generated:   %s/defconfig (mode 0600, outside the repository)\n' \
    "${GENERATED_DIR}"
else
  printf 'Passphrase:  none (--no-key); the handshake will report ENOKEY\n'
fi

# Which defconfig this build directory was last configured from.  The build
# underneath only runs the configure step when it has no .config yet, so a
# switch between the generated profile and the committed one is otherwise
# silently ignored: --no-key would rebuild the keyed image and report its hash,
# which is exactly the false result this flag exists to rule out.  A changed
# source therefore forces a clean build.
STAMP="${BUILD_DIR}/.k1-wpa-config-source"

if [ "${CLEAN}" -eq 0 ] && [ -f "${BUILD_DIR}/.config" ] &&
   [ "$(cat "${STAMP}" 2>/dev/null || printf '')" != "${CONFIG_PATH}" ]; then
  printf 'Reconfigure: the build directory was configured from another\n'
  printf '             defconfig, so this build starts clean\n'
  CLEAN=1
fi

ARGS=(--config "${CONFIG_PATH}" --build-dir "${BUILD_DIR}"
      --package --package-dir "${PACKAGE_DIR}" --jobs "${JOBS}")
if [ "${CLEAN}" -eq 1 ]; then
  ARGS+=(--clean)
fi

"${SCRIPT_DIR}/build_k1.sh" "${ARGS[@]}"
printf '%s\n' "${CONFIG_PATH}" > "${STAMP}"
